### ISSUE TITLE
Service Registry Fails Tests on Buildbot

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#1068]
**Describe the bug**
The service registry is increasingly failing the service registry unit tests with errors like this
```
[ERROR] Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 19.391 s <<< FAILURE! - in org.opencastproject.serviceregistry.impl.ServiceRegistryJpaImplTest
[ERROR] testIgnoreHostsInPriorityList(org.opencastproject.serviceregistry.impl.ServiceRegistryJpaImplTest)  Time elapsed: 2.167 s  <<< FAILURE!
java.lang.AssertionError
	at org.opencastproject.serviceregistry.impl.ServiceRegistryJpaImplTest.testIgnoreHostsInPriorityList(ServiceRegistryJpaImplTest.java:344)
```

This appears to be related to the processing service registration, and thus is likely related to #1047.  I can't reproduce this at home, but it seems to be semi common on ci.opencast.org.

**To Reproduce**
1. Build Opencast develop (cur 8.x).  Has been sighted on earlier versions as well.

**Comment by karendolan** [comment]
@gregorydlogan and @lkiesow I notice that Travis CI build throws the "Job with Id 1 cannot be deleted" during that test, and other similar sort of db errors occasionally on other tests. And then other times is doesn't. I also see this when I run the test locally. The assert error on line344 is testing "fromDb.setProcessorServiceRegistration(null);", that the persistence update was correct. Is it possible that the H2 db test framework is sometimes slower to respond, and sometimes faster? Is there a way to ensure that entity updates are completed before asserting on them, without setting a time delay?

**Comment by karendolan** [comment]
I notice there's a later version of H2 db engine. I'll do a little testing to see if that helps.
https://www.h2database.com/html/main.html

Updating the h2 didn't help, I'm looking at the PersistenceUtil.newTestEntityManagerFactory("org.opencastproject.common").[EDIT] was the right package... now testing resetting H2 between test methods... looks Ok to me. 
The unit is randomly having a hard time dealing with the serviceregistry activate()'s "cleanUndispatchableJobs":  
```
...
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "OC_ORGANIZATION_PROPERTY" not found; SQL statement:
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "OC_ORGANIZATION_NODE" not found; SQL statement:
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "OC_USER_REF_ROLE" not found; SQL statement:
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "SEQUENCE" not found; SQL statement:
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "OC_JOB" not found; SQL statement:
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "OC_USER" not found; SQL statement:
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "OC_GROUP" not found; SQL statement:
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "OC_ORGANIZATION" not found; SQL statement:
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "OC_ROLE" not found; SQL statement:
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "OC_USER_REF" not found; SQL statement:
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "OC_HOST_REGISTRATION" not found; SQL statement:
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "OC_SERVICE_REGISTRATION" not found; SQL statement:
...
```
I'll try mock the cleanUndispatchableJobs() to not do work

**Comment by gregorydlogan** [comment]
@karendolan this seems like a race condition to you as well right?  IMO, the easiest way to handle this is to run the SR's `deactivate()` method, which will stop job dispatching, thus preventing things from being in an inconsistent state when the state is checked.  Does that make sense to you?

**Comment by karendolan** [comment]
> @karendolan this seems like a race condition to you as well right? IMO, the easiest way to handle this is to run the SR's `deactivate()` method, which will stop job dispatching, thus preventing things from being in an inconsistent state when the state is checked. Does that make sense to you?

@gregorydlogan Ok, I just re-ingested your comment. You suspect that the dispatcher has re-dispatched the job to the correct host, so the host name has been reset, during the time of the test? That's easy to test! It would be awesome if this is the issue!

My appologies for the following, I went down a deep deep dive into the testing environment yesterday: ...part of the reason I went into the following deep dive is because of odd random logs from the test runs about when the test db cannot find data, that it can find in other test runs. 

[OLD] The items that the junits are testing appears to be properly functioning in production. It is unlikely that the failing tests expose an underlying problem with SR's running persistence. It is more likely to be a problem with the test environment. 

I do believe the test issue is a race condition, but with the underlying test environment resources or test scaffolding. Either because of deficiencies with the PersistenceUtil config of the H2 driver, or because the process is being starved of resources (RAM, disk space, or both). There are a lot of tests in the ServiceRegistryJpaImplTest that require the building of a big and complicated db structure. 

The following are the objects for "org.opencastproject.common". These have to be constructed and torn down in the temporary H2 databases. They are written on the test server hard drive, not in memory, for the many tests from the ServiceRegistryJpaImplTest. The Opencast module temporary databases are not cleaned up until the end of the maven test run. The opencast-serviceregistry unit tests happen towards the end of the full Opencast maven run when resources on the test server may be getting more stressed.

```
  <persistence-unit name="org.opencastproject.common" transaction-type="RESOURCE_LOCAL">
    <provider>org.eclipse.persistence.jpa.PersistenceProvider</provider>
    <non-jta-data-source>osgi:service/javax.sql.DataSource/(osgi.jndi.service.name=jdbc/opencast)</non-jta-data-source>
    <class>org.opencastproject.job.jpa.JpaJob</class>
    <class>org.opencastproject.security.impl.jpa.JpaUser</class>
    <class>org.opencastproject.security.impl.jpa.JpaGroup</class>
    <class>org.opencastproject.security.impl.jpa.JpaOrganization</class>
    <class>org.opencastproject.security.impl.jpa.JpaRole</class>
    <class>org.opencastproject.security.impl.jpa.JpaUser</class>
    <class>org.opencastproject.security.impl.jpa.JpaUserReference</class>
    <class>org.opencastproject.serviceregistry.impl.jpa.HostRegistrationJpaImpl</class>
    <class>org.opencastproject.serviceregistry.impl.jpa.ServiceRegistrationJpaImpl</class>
```

Do you know if there is a way to assess Travis CI environment resources during the build to see if it's running out of processing space?

Regards,
Karen

**Comment by rute-santos** [comment]
It seems the problem is that the job dispatcher is only stopped at the end of deactivate() so the job state is changed and, since the dispatcher is still running, the job can be dispatched/updated again... We are going to move the scheduledExecutor.shutdownNow(); to the beginning of activate so that the dispatcher does not try to dispatch the canceled job.

**Comment by karendolan** [comment]
> It seems the problem is that the job dispatcher is only stopped at the end of deactivate() so the job state is changed and, since the dispatcher is still running, the job can be dispatched/updated again.
@rute-santos & @gregorydlogan  I'm running the Travis CI build on the do-not-merge debugging pull 7 times, with all the messy debug logs, to verify that the priority queue junit does not fail. Then,  I'll force push a cleaned-up pull that just has the dispatch terminateAwait at the top of the service registry's deactivate as the fix for the service registry junits (which actually did their job to reveal an  underlying bug in the code!)

**Comment by karendolan** [comment]
@gregorydlogan successfully 5 builds on BuildBot so far, and no fails. Should the pull point to  8x/develop? It's a bug on the ServiceRegistryJpaImpl deactivate that also applies to 7x.

**Comment by gregorydlogan** [comment]
I'd point it at 7x since it's going to be breaking the build in the long term there as well.  It will get forward merged when the RMs do it.
