### ISSUE TITLE
When there is a series without a title, the metadata tabs break

### ISSUE THREAD

**Issue by JulianKniephoff** [opencast/opencast#1374]
After creating series with an empty title, which is surprisingly easy to do, considering that it is marked as a required field in the admin UI, you can't enter new or edit existing metadata anymore. The metadata tab is just empty:

![image](https://user-images.githubusercontent.com/123272/72820379-28b1d180-3c6f-11ea-9049-85d5eba0398f.png)

Apparently the `metadata` and `metadata.json` endpoints have a problem serializing this (which they have to do since they return a list of possible series to display). Interestingly the requests still succeed with a 200 code; they just don't have any content.

The serialization error can be seen in the log, and is ultimately due to some `NullPointerException`. Unfortunately I could not investigate further, yet.

**Comment by karendolan** [comment]
@JulianKniephoff I am surprised the Series service did not reject the creation of a series without a title. This seems  like an easy fix to enforce a default series title (i.e. `S-<seriesId>`) upon series creation.

[EDIT] I recommend the default series title because many places in the code expect a minimum ID and Title for both series and episode. If one or the other does not exist, it impacts more than the External API api and the Admin api.

**Comment by ebbertd** [comment]
@JulianKniephoff Is this fixed now?

**Comment by JulianKniephoff** [comment]
Seems to be fixed! :D
