### ISSUE TITLE
Correctly handle sub paths of Studio SPA (e.g. `/studio/settings`)

### ISSUE THREAD

**Issue by LukasKalbertodt** [opencast/opencast#1494]
Visiting `https://server/studio/settings` returns 404 (assuming you're already authenticated). The same goes for `/studio/about`. Currently everything under `/studio/*` is just a bunch of statically served files and `settings/index.html` does in fact not exist. Both of these links are used by Studio and work if they are reached through Studio (as JS handles everything). We just need to find a solution for when those links are requested directly.

I know that @darolfes did some investigation. Maybe you can quickly describe what you already tried and what didn't work?

**Comment by darolfes** [comment]
Two things were tested:

1. Registering an additional Service under `/studio`, which simply resolves `https://server/studio/settings`. This doesn't work, because two Services can't share the same Path.
2. A hacky Solution: Copying `/studio/index.html` to `/studio/settings/index.html`. This only works partially, because the `StaticResource` Servlet doesn't automatically redirect Directories to `./index.html` (the Service root Path `/studio` is an exception). Seems like this behavior can be easily adjusted, but the solution is overall quite hacky.
