### ISSUE TITLE
Wrong path in Asset Upload documentation

### ISSUE THREAD

**Issue by dr-pille** [opencast/opencast#1505]
**Describe the bug**
A clear and concise description of what you see:
https://docs.opencast.org/r/8.x/admin/#configuration/admin-ui/asset-upload/

etc/listproviders/event.upload.asset.options.properties

When I copy the path to the console, the computer sais "no"

**To Reproduce**
got to the guide, copy the path and paste at in the console.

**Environment Information**
 - OS: from at least 6.X up to 8.X

Should be work with an additional opencast in the path:
etc/opencast/listproviders/event.upload.asset.options.properties

**Comment by lkiesow** [comment]
The path can vary depending on how you install Opencast and there are an infinite amount of possible paths. That is why you have to transform all these configuration paths to the correct ones for your installation. Since you installed Opencast, you should also know the location of your configuration.

The documentation even explains this (just hover over `etc`):

> "etc" represents the configuration directory of Opencast.
This directory is often located at "/etc/opencast".
