### ISSUE TITLE
Release file is expired. How to workaround?

### ISSUE THREAD

**Issue by alevchuk** [opencast/opencast#1528]
**Describe the bug**
When I follow https://docs.opencast.org/r/8.x/admin/#installation/debs/ on AWS Debian GNU-Linux 8 -Jessie on step "Update your package listing" I get:

```
$ sudo apt-get update


W: There is no public key available for the following key IDs:
AA8E81B4331F7F50
E: Release file for http://cloudfront.debian.net/debian/dists/jessie-backports/InRelease is expired (invalid since 421d 20h 50min 51s). Updates for this repository will not be applied.
```

**Environment Information**
 - OS: Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux

**Comment by gregorydlogan** [comment]
@alevchuk You're seeing a couple of things here

1) Debian Jessie is currently LTS, and is about to be EOL (June 2020).
2) Your install is missing the relevant public key to verify the release file
3) It's possible that the relevant repository is no longer present given the end of life status for the release.

I would strongly recommend you upgrade to at least Debian 9 (stretch), or better yet Debian 10 (buster).  This isn't technically an Opencast issue, aside from the documentation needing a small update to indicate that Debian 8 and newer is supported, rather than explicitly stating Debian 8 and 9 :)

**Comment by gregorydlogan** [comment]
Docs are now updated -> closing.
