### ISSUE TITLE
Need Multi Node Documenation for Reverse-Proxying

### ISSUE THREAD

**Issue by nothing-fr** [opencast/opencast#1878]
**Describe the bug**
Need more documentation for reverse-proxying a multiple nodes opencast installation

**To Reproduce**
1. Install Admin Node
2. Install Worker Node
3. Install Presentation Node
4. Try to make it work behing reverse-proxy

**Environment Information**
 - OS: Ubuntu 18.04
 - Browser : Chrome
 - Opencast version : 8.6-2
- Reverse-Proxy : Apache 2.4

--------------------------------------------------------------

Here is what I'm trying to do : 

I have 3 nodes (opencast-admin.mydomain.com:8080 / opencast-pres.mydomain.com:8080 / opencast-worker.mydomain.com:8080), it's working correctly with these urls.

But I want to make it work like this for my users :

https://videos.mydomain.com > engage-ui
https://videos.mydomain.com/admin > admin-ui (from admin node)

Where i'm at so far : 
- I can access Engage
- Accessed Admin-ui is the one from the engage node and not the admin node
- When a video is uploaded and processed, the url for thumbnails and videos still are containing "opencast-pres.mydomain.com" (thus not working...)

I cannot find detailed documentation for Multiples Nodes configuration (with or without reverse-proxy) nor a detailed schematics for typical Opencast architectures.

Anyone have a clue on how to do this ?

**Comment by lkiesow** [comment]
You cannot – at least not without massive amount of work – use sub-paths for Opencast nodes.
Usually, people just use something like:

- videos.mydomain.com → presentation
- admin.videos.mydomain.com → admin

You can, of course, run Opencast on a single node or use the combined admin+presentation node with separate workers.

For a multi-node Opencast with reverse proxy, it's otherwise just a combination of these two documentation pages:
- https://docs.opencast.org/r/8.x/admin/#installation/multiple-servers/
- https://docs.opencast.org/r/8.x/admin/#configuration/https/nginx/

**Comment by nothing-fr** [comment]
ok, at least I'm sure it's not possible now... thank you !
