### ISSUE TITLE
Broken Paella Player Layout

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#2046]
Watching a single stream presenter video in Paella player leads to the video being displayed as a tiny thumbnail only, making the player completely unusable:

![Screenshot from 2020-11-05 01-19-43](https://user-images.githubusercontent.com/1008395/98182193-739e8c00-1f05-11eb-9101-b24af0da5f13.png)

To test this, ingest a video using:

```
curl -f -i -u admin:opencast https://develop.opencast.org/ingest/addMediaPackage/fast \
  -F 'flavor=presentater/source' \
  -F mediaUri=https://data.lkiesow.io/opencast/test-media/sintel_trailer-1080p.mp4 \
  -F title=presenter-only \
  -F creator=lk
```

This happens on `develop` (2020-11-05) and thus likely on `r/9.x`. Tested in a current Chromium and Firefox.

**Comment by lkiesow** [comment]
@miesgre, do you by any chance have time to take a look at this?

**Comment by miesgre** [comment]
@lkiesow The problem is you named you flavor `presentater` and by default paella only recognize `presenter` and `presentation`

See: 
https://github.com/opencast/opencast/blob/c910481af7ceb838bf739e7a7f9b6a0d6fe36d7d/etc/ui-config/mh_default_org/paella/config.json#L145-L151

You can configure your installation adding a new videoSet with the flavor `presentater`
```
{ "icon":"professor_icon.svg", "id":"presentater", "content":["presentater"]}, 
```

**Comment by lkiesow** [comment]
Good catch.
But then Paella should not show the video at all, should it?
It does show the video. Just very small.

**Comment by ferserc1** [comment]
In general, in paella player we don't add code that controls those failures derived from a bad configuration of the player, because we understand that this type of failures should never happen. The video is shown like this simply because after it is added to the player, a failure occurs when applying the layout, and that failure is not being controlled.

However, I have added an issue in the paella player repository to show this kind of error in the javascript console, to make it easier for website administrators to debug it:

[https://github.com/polimediaupv/paella/issues/628](https://github.com/polimediaupv/paella/issues/628)

**Comment by lkiesow** [comment]
I've dropped the „needs attention“ label since it definitely isn't that important given the current findings.

**Comment by lkiesow** [comment]
Closing this since Paella 7 is replacing Paella 6 soon anyway
