### ISSUE TITLE
Changes to start date & time not effective via External API

### ISSUE THREAD

**Issue by theodortruffer** [opencast/opencast#2115]
**Describe the bug**
When the metadata fields 'startDate' and 'startTime' of an event are manipulated through the External API, the changes are visible in the AdminUI but not when fetching the event via External API. 
I also noticed that the 'created' date/time is being updated instead (which is observable both via AdminUI and External API).

**To Reproduce**
* Update Event Metadata through External API 
  * POST /events/{eid}, {"metadata":"[{"label":"","flavor":"dublincore/episode","fields":[{"id":"startDate","value":"2020-11-13"},{"id":"startTime","value":"13:51"}],"loaded":false}]"}
* Fetch Event via External API
  * GET /events/{eid}
  * check the fields "start" and "created" - start keeps the old value, created is updated
* check the event metadata via AdminUI
  * both "created" and "start" are updated

**Environment Information**
 - OS: docker container (img: quay.io/opencast/allinone:8.7)
 - Browser: not relevant
 - Opencast version: 8.7
- External API version: v1.3.0

**Comment by mliradelc** [comment]
Hi Theodor, Thanks for noticing this behavior. :smiley: 

 I will look  into that. Sounds like that parameter is not  declared in the post code of the external api

**Comment by theodortruffer** [comment]
Hey Max, thank you for looking in to this! I forgot to mention: It's the same behavior if you update the start date/time via AdminUI.

**Comment by mliradelc** [comment]
Hi @theodortruffer 

Sorry for the late, I went to vacations a few days later I saw your enquiry. Now, I found the solution:

**Short answer:**

Try to use this format for the date and time
```json
'metadata':
[
  {
    "flavor":"dublincore/episode",
    "fields":[
      {
        "id":"startDate",
        "value":"2005-02-28"
      },
      {
        "id":"startTime",
        "value":"03:47:00.000Z"
      }
    ]
  }
]
```

**Long answer**

After looking over this issue, yes you are correct that there an issue with the POST and PUT in the external API, but it comes more in the realm of the documentation than the code itself (That is because a lot of patches and new versions of the API throught the years).

When you get the metadata from the Events API, you get the data in this way:

```json
...
{
                    "readOnly": false,
                    "id": "startDate",
                    "label": "EVENTS.EVENTS.DETAILS.METADATA.START_DATE",
                    "type": "date",
                    "value": "2005-02-28T03:47:00.000Z",
                    "required": false
                },
...
```

The start time and the start date are "merged" in only one variable. The API for modifying (In PUT and POST) looks for the separate values. Those values need to be in a specific format:

```
startDate: YYYY-MM-DD
startTime: HH:MM:SS.SSSZ
```
In the case of `startTime` is set for UTC time, instead of local time.


Neverthless, there is another issue with the creation date, is also modified as you say.


I was to modify the code to make the request looks like the answer in the external api, but I think with this Answer you can get this out.  Also, I recommend strongly to use `Postman` or any other program for API development, makes more easy the testing in the API.


Please test that solution and tell me :D

**Comment by theodortruffer** [comment]
Hey Max

Unfortunately, that doesn't solve our problem. But I found something else: the changed start date appears correctly when calling '/api/events/[id]/metadata', but incorrectly when calling 'api/events/[id]'. So the problem seems to be the field 'start' inside the event data, not the actual metadata. I guess the metadata field value should be written to the event data field at some point?

Could you have a look at this? Of course we could just use the /metadata endpoint, but that would generate additional requests and impact the performance of the plugin.

Thanks a lot!
Theo

**Edit:** The date format didn't seem to have any impact - the metadata fields worked both ways and the event data field didn't. I am testing with the 'Insomnia' client btw.

**Comment by mliradelc** [comment]
Hi Theo

Now I understand you better, because when I checked, I was checking only the metadata field.  But the thing that Opencast call metadata is only the Dublincore file. There is another set of "metadata" that is call itself.

In the case of the metadata "outside" the Dublincore file, the start is called `TechnicalStartTime`, from what I know is the real time when the file was added. And there is the `created` field, that is the date and time that the user can change. Anyways, I will ask further if this is a bug or a "Feature". :wink: 


Here is a GET call from an event That I ingested and then I use POST /apt/events/{{event-id}} to modify the `startTime` and the `startDate`. Note: I deleted some fields to keep compact this post and don't interfere with the disscussion.


```json
{
    "identifier": "d6e6d8e8-908e-4ad7-95d3-a5e290e7961e",
    "creator": "Opencast Project Administrator",
    "metadata": [
        {
            "flavor": "dublincore/episode",
            "title": "EVENTS.EVENTS.DETAILS.CATALOG.EPISODE",
            "fields": [
                {
                    "readOnly": false,
                    "id": "title",
                    "label": "EVENTS.EVENTS.DETAILS.METADATA.TITLE",
                    "type": "text",
                    "value": "api ingest edit via POST",
                    "required": true
                },
                {
                    "readOnly": false,
                    "id": "startDate",
                    "label": "EVENTS.EVENTS.DETAILS.METADATA.START_DATE",
                    "type": "date",
                    "value": "2005-02-28T03:47:00.000Z",
                    "required": false
                },
                {
                    "readOnly": false,
                    "id": "duration",
                    "label": "EVENTS.EVENTS.DETAILS.METADATA.DURATION",
                    "type": "text",
                    "value": "00:00:00",
                    "required": false
                },
                {
                    "readOnly": true,
                    "id": "created",
                    "label": "EVENTS.EVENTS.DETAILS.METADATA.CREATED",
                    "type": "date",
                    "value": "2005-02-28T03:47:00.000Z",
                    "required": false
                },
                {
                    "readOnly": true,
                    "id": "publisher",
                    "label": "EVENTS.EVENTS.DETAILS.METADATA.PUBLISHER",
                    "type": "text",
                    "value": "",
                    "required": false
                },
                {
                    "readOnly": true,
                    "id": "identifier",
                    "label": "EVENTS.EVENTS.DETAILS.METADATA.ID",
                    "type": "text",
                    "value": "d6e6d8e8-908e-4ad7-95d3-a5e290e7961e",
                    "required": false
                }
            ]
        }
    ],
    "presenter": [
        "Christian Rolfs"
    ],
    "created": "2005-02-28T03:47:00Z",
    "is_part_of": "ef6be997-a319-4493-944b-32d19c486bec",
    "subjects": [
        "John Clark",
        "Thiago Melo Costa"
    ],
    "start": "2021-02-02T10:45:13Z",
    "description": "A great description",
    "language": "",
    "source": "",
    "title": "api ingest edit via POST",
    "processing_state": "SUCCEEDED",
    "duration": 0,
    "license": "",
    "archive_version": 2,
    "contributor": [],
    "series": "Test series",
    "has_previews": true,
    "location": "",
    "rightsholder": "",
    "publication_status": [
        "internal",
        "engage-player"
    ],
    "status": "EVENTS.EVENTS.STATUS.PROCESSED"
}
```



From here I think you have two workarounds that can work:
1. Use the "Created" field
2. In the GET event-id add the parameter `withmetadata=true`.

But as I said before, the naming for me is not very clear also. `start`  it should be something like `recordingDate` and `recodingTime`. For the event creation in the server should be `creationDate` for example. Anyways, because this affects the API is not something simple as rename it, because can break another peoples integrations.

**Comment by theodortruffer** [comment]
Thanks for the explanation, that's exactly the knowledge about Opencast that I'm lacking! It is quite confusing sometimes :) 

I'm a bit afraid that `withmetadata=true` could affect our performance. But using the Created field as workaround seems like a good idea. I will have a look at that.

I'm curious whether they consider this a bug. ;) Thanks for your effort anyways!

**Comment by karendolan** [comment]
The "startDate" is not a dublinCore term. It's confusing to include it as dublincore flavor.  The DublinCore temporal is used for adminUI technical start date. https://www.dublincore.org/specifications/dublin-core/dcmi-terms/

**Comment by mliradelc** [comment]
@theodortruffer It's been a while since this issue was open, do you think the explanation solved for you or needs to be addressed in more depth?

**Comment by theodortruffer** [comment]
@mliradelc I think all should be clear now. I'll fix it in the plugin (we'll have to load and use the metadata).
