### ISSUE TITLE
Migrate from Dependabot Preview to Dependabot

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#2242]
Dependabot is moving natively into GitHub.
We should migrate at some point:
https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates#enabling-dependabot-version-updates

**Comment by gregorydlogan** [comment]
Bringing this up here since we might end up losing the conversation in the PR otherwise: Do we need the rest of the rules?  In the case of the chromedriver rule I'm pretty sure we don't - we shouldn't be depending on a (potentially old) version of the driver, right?

The Paella version can also likely go, since we're already past the 6.4 limit in the depdendabot config.  I would also assume that the Paella devs would keep us up to date as things move forward.

Typescript.... that I'm less sure about.  @LukasKalbertodt @Arnei you're either working on stuff with typescript, or assigned to PRs reviewing them.  Should dependabot be filing PRs to automatically upgrade things?

**Comment by lkiesow** [comment]
I'm pretty sure we don't need any, and I've introduced most (all) of them in the first place
