### ISSUE TITLE
Filenames of videos, thumbnails, preview can be too long thus workflow fails

### ISSUE THREAD

**Issue by MatteBili** [opencast/opencast#2699]
**Describe the bug**
The filenames of any process file can be too long, therefore tools like ffmpeg etc. fail with error and the whole workflow might fail.

`2021-06-09T15:53:12,055 | INFO  | (EncoderEngine:461) - /srv/opencast/workspace/mediapackage/b39f3e94-81c0-48ac-9a5f-abb07a208c2c/bf15e33c-0eec-4855-bd92-ca30514723e5/2021_06_09_13_36___WS13_1_Rare_species_may_act_as_problem_solvers_in_critical_situations_of_the_bacterial_co_occurence_network_in_cystic_fibrosis_airways___Marie_M*****_P***__presentation__OC_Studio__8c349465-3440-4563-b2ea-4d8952b6d4f9-preview-composite.mp4: File name too long`

Here so many informations will be concatted together, which the system itself would not need: date, title of the recording, name of the presenter type of the video (presenter/presentation), roomname plus uuids etc.
Seems to me, that these are for human readability only.
My opinion of naming and handling files, internally work with uuids only and use human-readable naming only for downloads and respect filesystem specific conventions (pull human-readable data from db & truncate some info e.g. title).

**To Reproduce**
1. Go to 'Add Event'
2. Enter Title of at least 150 characters approx.
3. Enter Presenter(s) of at least 20 characters approx.
4. Start Studio Upload Workflow
5. Check opencast.log as the webfrontend yields unspecific error details

**Environment Information**
 - OS: Debian Stretch
 - Browser any
 - Opencast version with minor release <=8.11

**Comment by lkiesow** [comment]
Since this is related to Opencast Studio which has a separate issue tracker, would you mind reporting this at
https://github.com/elan-ev/opencast-studio/issues

**Comment by Rillke** [comment]
I would be in favor if Opencast would resolve this for the clients using the ingest and upload APIs (either reject or truncate). It makes integrations unnecessary complex otherwise, see for example 

* https://github.com/elan-ev/studip-opencast-plugin/issues/372
* https://github.com/elan-ev/studip-opencast-plugin/issues/489
* https://github.com/Opencast-Moodle/moodle-block_opencast/issues/204

**Comment by gregorydlogan** [comment]
If we're munging the names, why not rename the file to a UUID, and then store the input filename as an asset property?

**Comment by lkiesow** [comment]
That would just move the problem to a different location. Once you distribute the files, you would then end up with the same problem unless you also build the UUID +  storing the filename separately into the distribution channels, which then means that this could cause issues when users try downloading the files (that's the reason why this was already fixed in Studio). So you likely will end up with a lot of work and a complex system for little gain. I would rather just limit the filenames to ~75 characters and be done with it. Much simpler and I doubt anyone will complain that they can't have a novel as a filename. Let me propose a patch…
