### ISSUE TITLE
Is it possible to prevent downloading video with the feature of stream security?

### ISSUE THREAD

**Issue by fishfree** [opencast/opencast#3051]
Even we disable download tab in the Paella player, it's still very easy to download video via HTML source. I read the stream security configuration in the [doc](https://docs.opencast.org/r/10.x/admin/#configuration/stream-security/), is it possible to prevent downloading video with this feature? If not, are there any other options?

**Comment by lkiesow** [comment]
No, that does not prevent downloads at all. Just sharing the links is a bit harder.
In the end, it's basically impossible to completely prevent this.
You can make it somewhat harder though, if you switch to streaming instead of using progressive download.

I guess that answers the question → closing this issue
