### ISSUE TITLE
asset-manager move to S3 duplicates identical files 

### ISSUE THREAD

**Issue by ts23** [opencast/opencast#3164]
**Describe the bug**

When the asset manager moves files into S3 using moveById, moveByDate or moveByIdAndDate multiple versions of episodes are moved to S3. This is done by creating a bunch of subjobs where each is moving a single version of an episode. These subjobs can run in parallel which can cause duplication of assets on S3 as multiple files with identical checksum can be moved at the same time.

expected behaviour would be that each file has a unique checksum on S3 and other files are mapped through the asset mapping table in the database.  

**To Reproduce**
Steps to reproduce the behaviour:
1. Create multiple versions of an episode running workflows on local-filesystem
2. trigger the Rest Endpoint in /assets/moveById with the mpId and the target id "aws-s3"
3. be (un)lucky
4. Check the s3-bucket of the mediapackage and the Database

**Environment Information**
 - Opencast version 8 - *

**Comment by rute-santos** [comment]
Hi @ts23 ,
We noticed this too some time ago and our fix was not to spawn sub-jobs when archiving by date but instead execute the move sequentially. It's less efficient, but doesn't duplicate anything, which is fine with us because we run it overnight. We only use the option to archive by date. We still have Opencast 5.x and our solution is not pretty. I can share it with you if you are interested, but it probably does not apply to earlier versions so not "contributable" as it currently is.
Thanks,
Rute

**Comment by ts23** [comment]
This is pretty much exactly what my fix is doing on a byId basis, so it could theoretically duplicate items if two independent MPs contain the identical (by checksum) files and are moved to S3 at the same time
