### ISSUE TITLE
ACL are missing since the UI change

### ISSUE THREAD

**Issue by mliradelc** [opencast/opencast#5016]
**Describe the bug**

Hi, we are experimenting with two issues since the new UI change in the ACL.

1.- You can't search for External Roles
2.- While the ACL from the existing events is selected, the ACL doesn't show the users, only the local roles.

![acl error](https://github.com/opencast/opencast/assets/8040628/4d24a67f-dea1-46ee-bfef-d193e07b814d)

**To Reproduce**

Enable ACL with LDAP

**Expected behavior**

It should show the users. and the role of external search should work.

Important info: We are using LDAP. The logging and roles work as intended, only the ACL panel in the admin UI.

I'm not very well versed with the front end. If someone can help me debug this issue, I can find and fix the problem's root. The dev tools from the browser show that roles exist and are retrieved.

**Comment by KatrinIhler** [comment]
I'm gonna cc @Arnei on this since this was his PR. :D

**Comment by Arnei** [comment]
Noob question: What are external roles? How can I set up my local Opencast instance to have external roles? 

The frontend gets its roles from `/admin-ng/acl/roles.json`. Are external roles returned from that endpoint?

**Comment by reiferschris** [comment]
@Arnei I'm not sure if external roles is the right term. The typical LDAP connection does not import users in to opencast. They are retrieved from LDAP and then assigned roles within opencast for a session/login. The derived roles e.g. `ROLE_USER_BBUNNY` are then used in ACLs.
To answer your question: No those roles are not in the `/admin-ng/acl/roles.json` but in `admin-ng/event/59b50b25-69e2-4886-8043-12e7717a382b/access.json` 
It seems the endpoint you are referring to just lists the users and groups that are in Openasts DB

**Comment by mliradelc** [comment]
1. On `etc/custom.properties`:

```
# Optional custom roles pattern (regular expression). Roles matching this pattern can be added to ACLs.
org.opencastproject.security.custom.roles.pattern=^(ROLE_USER_[A-Z][A-Z0-9]*|LDAP_[A-Z][A-Z0-9]*_ADMIN|[0-9]+_(LEARNER|INSTRUCTOR))$
```

2. Then you need to create a new LDAP config file using the template `etc/org.opencastproject.userdirectory.ldap.cfg.template`

3. On `org.opencastproject.organization-mh_default_org.cfg`:

     -  Set true the external role display:
```
# Set a flag to display External Roles on User modal
#
# Value: <boolean>
# Default: false
prop.adminui.user.external_role_display=true
```

4. Finally, enable LDAP in the security file (Normally `security/mh_default_org.xml`).



If I recall correctly those are all the steps you need to try LDAP. ~I will update shortly to give you a mini ldap server you can run with docker compose locally~. Here it is: https://github.com/rroemhild/docker-test-openldap

**Comment by Arnei** [comment]
> @Arnei I'm not sure if external roles is the right term. The typical LDAP connection does not import users in to opencast. They are retrieved from LDAP and then assigned roles within opencast for a session/login. The derived roles e.g. `ROLE_USER_BBUNNY` are then used in ACLs. To answer your question: No those roles are not in the `/admin-ng/acl/roles.json` but in `admin-ng/event/59b50b25-69e2-4886-8043-12e7717a382b/access.json` It seems the endpoint you are referring to just lists the users and groups that are in Openasts DB

Thanks for the clarification. The Admin UI also uses the endpoint you described (`admin-ng/event/{event-ud}/access.json`) to get the roles for the event. But if I understand Max correctly both endpoints should return derived roles, right? Since you want to be able to add derived rules not currently present in the event?

**Comment by Arnei** [comment]
> 1. On `etc/custom.properties`:
> 
> 
> ```
> # Optional custom roles pattern (regular expression). Roles matching this pattern can be added to ACLs.
> org.opencastproject.security.custom.roles.pattern=^(ROLE_USER_[A-Z][A-Z0-9]*|LDAP_[A-Z][A-Z0-9]*_ADMIN|[0-9]+_(LEARNER|INSTRUCTOR))$
> ```
> 
>     2. Then you need to create a new LDAP config file using the template `etc/org.opencastproject.userdirectory.ldap.cfg.template`
> 
>     3. On `org.opencastproject.organization-mh_default_org.cfg`:
>        
>        * Set true the external role display:
> 
> 
> ```
> # Set a flag to display External Roles on User modal
> #
> # Value: <boolean>
> # Default: false
> prop.adminui.user.external_role_display=true
> ```
> 
>     4. Finally, enable LDAP in the security file (Normally `security/mh_default_org.xml`).
> 
> 
> If I recall correctly those are all the steps you need to try LDAP. ~I will update shortly to give you a mini ldap server you can run with docker compose locally~. Here it is: https://github.com/rroemhild/docker-test-openldap

Thanks for the detailed explanation and the link to the docker-test-ldap. I'll try to test with that and see if I can find something obviously wrong.

**Comment by mliradelc** [comment]
> both endpoints should return derived roles, right? Since you want to be able to add derived rules not currently present in the event?

As Christoph said, `admin-ng/event/{{event_id}}/access.json` give the roles list that is in the media package.

While `/admin-ng/acl/roles.json` gives you the list of roles saved in Opencast locally.


Users when they logged into opencast, they get the ROLE_USER_{user_id} as stated on `acl.default.create.properties`

**Comment by Arnei** [comment]
The docker container you suggested does not work. Any other way I can spin up a test ldap with custom roles?

**Comment by mliradelc** [comment]
I'm sorry to hear that the docker-compose didn't work. 

Try this server https://www.forumsys.com/2022/05/10/online-ldap-test-server/. I used it in the past for troubleshooting. I just tested it, and it is working.

With that command, you can test if it connects.
```
ldapsearch -x -LLL -H ldap://ldap.forumsys.com:389 -b "dc=example,dc=com" -s sub "(objectClass=person)" cn
```

**Comment by Arnei** [comment]
Right, that server is very helpful for doing some basic ldap tests. But how does it help me test with custom roles? Can't make changes to the server there can I?

**Comment by reiferschris** [comment]
Why would you want to make changes on that server? It has all you need. A few users that you can search for from opencast.
This should be the settings you need for connecting to that ldap-server
in `org.opencastproject.userdirectory.ldap-test.cfg`
```
org.opencastproject.userdirectory.ldap.id=test

org.opencastproject.userdirectory.ldap.url=ldap.forumsys.com

org.opencastproject.userdirectory.ldap.searchbase=ou=mathematicians,dc=example,dc=com
org.opencastproject.userdirectory.ldap.searchfilter=(uid={0})

org.opencastproject.userdirectory.ldap.roleattributes=cn

org.opencastproject.userdirectory.ldap.userDn=cn=read-only-admin,dc=example,dc=com
org.opencastproject.userdirectory.ldap.password=password

org.opencastproject.userdirectory.ldap.userattributes.name=cn
```
and in `security/mh_default_org.xml`
```
  <!-- ################ -->
  <!-- # LDAP Support # -->
  <!-- ################ -->


  <bean id="contextSource"
    class="org.springframework.security.ldap.DefaultSpringSecurityContextSource">
    <!-- URL of the LDAP server -->
    <constructor-arg value="ldap://ldap.forumsys.com:389" />
    <!-- "Distinguished name" for the unprivileged user -->
    <!-- This user is merely to perform searches in the LDAP to find the users to login -->
    <property name="userDn" value="cn=read-only-admin,dc=example,dc=com" />
    <!-- Password of the user above -->
    <property name="password" value="password" />
  </bean>

    <bean id="userDetailsMapper" class="org.opencastproject.security.ldap.OpencastUserDetailsMapper">
      <constructor-arg ref="userDetailsService" />
    </bean>
    

  <bean id="ldapAuthProvider"
    class="org.springframework.security.ldap.authentication.LdapAuthenticationProvider">
    <constructor-arg>
      <bean
        class="org.springframework.security.ldap.authentication.BindAuthenticator">
        <constructor-arg ref="contextSource" />
        <property name="userDnPatterns">
          <list>
            <!-- Dn patterns to search for valid users. Multiple "<value>" tags are allowed -->
            <value>uid={0},ou=mathematicians,dc=example,dc=com/value>
          </list>
        </property>
        <!-- If your user IDs are not part of the user Dn's, you can use a search filter to find them -->
        <!-- This property can be used together with the "userDnPatterns" above -->
        <!--
        <property name="userSearch">
          <bean name="filterUserSearch" class="org.springframework.security.ldap.search.FilterBasedLdapUserSearch">
            <! - - Base Dn from where the users will be searched for - - >
            <constructor-arg index="0" value="ou=GroupName,dc=my-institution,dc=country" />
            <!- - Filter to located valid users. Use {0} as a placeholder for the login name  - - >
            <constructor-arg index="1" value="(uid={0})" />
            <constructor-arg ref="contextSource" />
          </bean>
        </property>
        -->
      </bean>
    </constructor-arg>
    <!-- Retrieve user and attributes from opencasts user details service -->
    <property name="userDetailsContextMapper" ref="userDetailsMapper"/>
    <!-- Defines how the user attributes are converted to authorities (roles) -->
    <!-- Output is ignored if used together with userDetailsMapper -->
    <!-- constructor-arg ref="authoritiesPopulator" /-->
  </bean>
```
and a bit further down in `security/mh_default_org.xml`
```
 <!-- Uncomment this as an alternative to the userDetailsMapper -->
  <!-- Make sure you provide the same instanceId you used in org.opencastproject.userdirectory.ldap-….cfg -->

  <osgi:reference id="authoritiesPopulator" cardinality="1..1"
                  interface="org.springframework.security.ldap.userdetails.LdapAuthoritiesPopulator"
                  filter="(instanceId=test)"/>
```
As stated in the comments above, you need to make sure that the .cfg file and that instanceId match.

I hope this helps. I have not tested this since I don't have a local opencast instance. 
Edit: I used the `mathematicians` group since I don't know if/how it works without one. So make sure to only try users from that group. :)

**Comment by mliradelc** [comment]
Workaround: Reverting #4487 (Going back to the old ACL UI). But this is for the UI of 13.x.   I haven't tested yet how behaves on 14.x this workaround.

**Comment by scharnkn** [comment]
Is there a workaround for this issue on OC 14.x? We used to be able to create ACLs for our Active Directory users (which are not persisted in the database) by using a custom role pattern for `ROLE_USER_XXX`. At the moment, we cannot do that anymore and have to manually sync all our Active Directory users to the Opencast database.

I really do appreciate the UI change in general, but unfortunately it broke some functionality for us.

**Comment by Arnei** [comment]
Finally got around to taking another look at this, since Max provided my with his LDAP config (thanks again!).

I think I now have a better understanding of how the external role selection works. All this really boils down to is that a custom role pattern can be defined in `etc/custom.properties` like

```
# Optional custom roles pattern (regular expression). Roles matching this pattern can be added to ACLs.
org.opencastproject.security.custom.roles.pattern=^(ROLE_USER_[A-Z][A-Z0-9]*|LDAP_[A-Z][A-Z0-9]*_ADMIN|[0-9]+_(LEARNER|INSTRUCTOR))$
```

So when a string like `ROLE_USER_GIBBERISH` was searched for in the dropdowns in the access policy tab, that string would be matched against the custom role pattern. If successful, the string could then be added to the event/series as a role.

![Bildschirmfoto vom 2023-09-20 10-45-17](https://github.com/opencast/opencast/assets/14070005/ad48278c-5242-43ca-8a16-5dfba13ddf76)

So the old process had nothing to do with looking up users or roles in LDAP in other external user-/role-providers. It simply allowed users to define whatever role they wanted as long as it matched the custom roles pattern defined in `etc/custom.properties`. This is still how it works for non-user roles. Or at least this is how I think it works, please correct me if I'm wrong.

-------

So how should this work in the future? Mainly I'm wondering if people want to be able to add whatever users they want, or if we should actually check whether the user they are trying to enter is actually a valid user in Opencast or external user providers. So we could:

- Make use of custom.role.patterns again. So when `GIBBERISH` is entered into a "user" dropdown in the access policy tab, Opencast would convert that to `ROLE_USER_GIBBERISH` and check if it matches the custom role pattern in `etc/custom.properties`. If true, the Admin UI would then allow it to be added to the event/series. This will still work if `GIBBERISH` is not a valid user, the ui will then simply display the user "gibberish" as non-existing.

- Check if the entered string maps to a valid username via i.e. the `admin-ng/{username}.json` endpoint. So when `GIBBERISH` is entered into a "user" dropdown in the access policy tab, Opencast would check if `GIBBERISH` is a valid user anywhere (Opencast DB, LDAP, etc.). Only if Opencast gets confirmation that `GIBBERISH` is indeed valid would the Admin UI allow it to be added to the event/series.

I don't have a strong opinion on either approach, I'm more interested in hearing what our community members who use this in production think.

**Comment by mliradelc** [comment]
As discussed in the Dev meeting on 26. Sept. The first option (Make use of `custom.role.patterns` again) is the best course of action.

**Comment by mliradelc** [comment]
@Arnei There something that I completely forgot to mention to you.

If you have roles set in the previous UI and apply your commit, those roles will appear in the new UI as blank fields in the users section of the new UI.
