### ISSUE TITLE
Feature request: privacy statement and imprint

### ISSUE THREAD

**Issue by pselsa** [opencast/opencast#5614]
When using the admin frontend for more than a few admins (e.g. lecturers that upload videos directly from the admin ui), there has to be a way to supply a privacy statement and an imprint. Both should off course be configurable and being linked in the UI´s footer.

Frontend issue: https://github.com/opencast/opencast-admin-interface/issues/297

**Comment by pselsa** [comment]
Idea of implementation:

- Provide a config file for each privacy statement and imprint
  - Format plain html?
  - Location /etc/ui-config/mh_default_org/admin-ui?
- Both files can then be accessed via e.g. /ui/config/admin-ui/privacy.html and be used by the admin-ui frontend

**Comment by gregorydlogan** [comment]
+1 for putting them in `ui-config/$orgId/admin-ui` since this is going to need to be configurable.  Plain text or HTML would definitely make the most sense since whatever it placed there would end up being rendered in the context of the existing UI - think Adopter Registration's Terms Of Use like this 
![image](https://github.com/opencast/opencast/assets/5639561/8cf135ed-7d65-453f-a9d6-e54920a949c1)

You're certainly welcome to include the privacy statement into the old admin UI, however I probably would not bother.  The short term (OC 16/17) goal is to remove it entirely :)

**Comment by pselsa** [comment]
Cool thanks for the feedback! FYI: the terms of use have an own issue: https://github.com/opencast/opencast/issues/5613
