### ISSUE TITLE
OC16 Seach Index does not support URL signing

### ISSUE THREAD

**Issue by olio2** [opencast/opencast#5957]
From #5597 
"Notably, I did not include URL signing support with this. If this is a deal breaker we can work on it later."

This leads to Stream Security not working anymore.

In our case we have to disable stream security on our Wowza Server to play videos again with Opencast 16.

This is still documentented[1] but does not work anymore.

[1] https://docs.opencast.org/r/16.x/admin/#configuration/stream-security/stream-security-config/#configuration-of-wowza-url-signing

**Comment by pselsa** [comment]
Hei @gregorydlogan, i am afraid this is definitely a dealbreaker since we now cant use the paella player anymore since all our urls have to be signed. Only thing we could do would be to use multi tenancy, but i was advise against that in the chat. Could you have a look into that and re-implement the url signing for the search module?

**Comment by lkiesow** [comment]
We discussed this multiple times when we talked about the migration. Both, when we first discussed the draft I created and then when Greg did the final implementation. Long story short: We can't implement it in the same way we did before. Or rather, it would have series drawbacks.

The main problem here is that search can return thousands of events. All of them we would need to modify on the fly when implementing this. That's problematic.

That doesn't mean, you can't do anything about this:

- If you use the search results somewhere else, you could have that somewhere sign the URLs before passing them to Paella. This requires a backend, though.
- You could use the [Opencast's signing endpoint](https://develop.opencast.org/docs.html?path=/signing#sign-2) to sign the URLs.
- You could implement something like `/search/<id>.json` with signing support which explicitly returns just one event (that should work for Paella) and which supports signing. In theory, you could also keep the current API and make signing work only if the `?id=` parameter is being used. I think using a new path would be less confusing, though.

I would probably go for the third option, iif I would really need it. That's additional development, though it shouldn't be too complicated.

Another option would be to avoid Wowza altogether. If you use this for VOD, Opencast can do HLS internally with just a workflow change.

**Comment by pselsa** [comment]
Hei @lkiesow thanks for the explanation. To be honest, i feel kind of frustrated right now since we relied on the url signing feature and also use the engage player and now it feels like i was responsible to make that work again (since no one else really uses either of these features?). I would be more happy if we could agree that this is a bug and not a feature and could work on it together. I will have a look to your third option, but since i am new to oc development (and actually are only payed a few hours the week to administrate our oc setup) i cant guarantee that i have enough resources to implement that in a reasonable way, but i will give my best.

**Comment by pselsa** [comment]
Can someone give me a quick hand with that, my idea is now to manipulate all urls from the [search result](https://github.com/opencast/opencast/blob/904bf85b0c8085b7f157ebf38e1fc3ab2252f0c9/modules/search-service-impl/src/main/java/org/opencastproject/search/endpoint/SearchRestService.java#L422) with `decodeURI` from the `SigningMediaPackageSerializer`, is there some instance of the serializer that i can use or would i have to instantiate one? Or am i completely on the wrong path here?

**Comment by pselsa** [comment]
Ok got it working now

**Comment by lkiesow** [comment]
> I would be more happy if we could agree that this is a bug and not a feature and could work on it together. 

Sorry for that. I was just trying to communicate the reasoning behind the decision. It was talked about in the technical meetings and then removed (or rather not re-build in this case) since no one seemed to care and no one spoke up. It's not that it cannot come back, and it's good to see that you found a way.

For working on this together, I'm happy to help out with lots of things and do so all the time in the community. But we don't use this, and I can't really spend all my time investigating features that we don't use or need for others, while there are still a lot of things for me to work on we actually do need.

I think, the best way to avoid something like this in the future would be to test things early so you can catch changes which are problematic for you and complain about them. If we know something is a problem beforehand, we as a community try to avoid changes like that or work with you to find the best way forward. If you complain about things months after the change has happened, this is much harder, since developers moved on and are now working on something else.

That being said, I'll try to test your patch this week. If we get it merged, it will become part of the 16.3 release, which should be released in about two weeks.

**Comment by pselsa** [comment]
Hei Lars, thanks for your words, appreciate it! Didnt mean to push you here and it makes totally sense that my complain came way too late, gonna try to test things earlier next time. And thanks for having a look into the patch :)
